<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="U-DL1J8D3" failures="1" tests="5" name="Surefire test" time="21.847" errors="0" timestamp="2024-06-01T11:26:58 IST">
  <testcase classname="test.NewTest" name="f" time="8.877"/>
  <testcase classname="test.NewTest" name="f1" time="6.112">
    <failure type="java.nio.file.FileSystemException" message=": The process cannot access the file because it is being used by another process">
      <![CDATA[java.nio.file.FileSystemException: : The process cannot access the file because it is being used by another process
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
at java.base/sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:180)
at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:282)
at java.base/java.nio.file.Files.copy(Files.java:1304)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:850)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:756)
at test.NewTest.f1(NewTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- f1 -->
  <testcase classname="test.NewTest" name="m1" time="0.001"/>
  <testcase classname="test.NewTest" name="m2" time="6.809"/>
  <testcase classname="test.NewTest" name="m3" time="0.0"/>
</testsuite> <!-- Surefire test -->
